// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EncryptFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateEncryptionKey(arg1:number):Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string):Promise<string>;

export function SelectSourceFile(arg1:string):Promise<string>;
