// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecryptFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptFile'](arg1, arg2, arg3);
}

export function EncryptFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['EncryptFile'](arg1, arg2, arg3);
}

export function GenerateEncryptionKey(arg1) {
  return window['go']['main']['App']['GenerateEncryptionKey'](arg1);
}

export function SelectSaveFile(arg1, arg2) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2);
}

export function SelectSourceFile(arg1) {
  return window['go']['main']['App']['SelectSourceFile'](arg1);
}
